llama_block_prefix = [['model.layers.0.'], ['model.layers.1.'], ['model.layers.2.'], ['model.layers.3.'],
                          ['model.layers.4.'], ['model.layers.5.'], ['model.layers.6.'], ['model.layers.7.'],
                          ['model.layers.8.'],
                          ['model.layers.9.'], ['model.layers.10.'], ['model.layers.11.'], ['model.layers.12.'],
                          ['model.layers.13.'],
                          ['model.layers.14.'], ['model.layers.15.'], ['model.layers.16.'], ['model.layers.17.'],
                          ['model.layers.18.'],
                          ['model.layers.19.'], ['model.layers.20.'], ['model.layers.21.'], ['model.layers.22.'],
                          ['model.layers.23.'],
                          ['model.layers.24.'], ['model.layers.25.'], ['model.layers.26.'], ['model.layers.27.'],
                          ['model.layers.28.'],
                          ['model.layers.29.'], ['model.layers.30.'], ['model.layers.31.']]

chatglm_block_prefix = [['transformer.encoder.layers.0.'], ['transformer.encoder.layers.1.'], ['transformer.encoder.layers.2.'],
                      ['transformer.encoder.layers.3.'], ['transformer.encoder.layers.4.'], ['transformer.encoder.layers.5.'],
                      ['transformer.encoder.layers.6.'], ['transformer.encoder.layers.7.'], ['transformer.encoder.layers.8.'],
                      ['transformer.encoder.layers.9.'], ['transformer.encoder.layers.10.'], ['transformer.encoder.layers.11.'],
                      ['transformer.encoder.layers.12.'], ['transformer.encoder.layers.13.'], ['transformer.encoder.layers.14.'],
                      ['transformer.encoder.layers.15.'], ['transformer.encoder.layers.16.'], ['transformer.encoder.layers.17.'],
                      ['transformer.encoder.layers.18.'], ['transformer.encoder.layers.19.'], ['transformer.encoder.layers.20.'],
                      ['transformer.encoder.layers.21.'], ['transformer.encoder.layers.22.'], ['transformer.encoder.layers.23.'],
                      ['transformer.encoder.layers.24.'], ['transformer.encoder.layers.25.'], ['transformer.encoder.layers.26.'],
                      ['transformer.encoder.layers.27.']]
bloom_block_prefix = [['transformer.h.0.'], ['transformer.h.1.'], ['transformer.h.2.'],
                      ['transformer.h.3.'], ['transformer.h.4.'], ['transformer.h.5.'],
                      ['transformer.h.6.'], ['transformer.h.7.'], ['transformer.h.8.'],
                      ['transformer.h.9.'], ['transformer.h.10.'], ['transformer.h.11.'],
                      ['transformer.h.12.'], ['transformer.h.13.'], ['transformer.h.14.'],
                      ['transformer.h.15.'], ['transformer.h.16.'], ['transformer.h.17.'],
                      ['transformer.h.18.'], ['transformer.h.19.'], ['transformer.h.20.'],
                      ['transformer.h.21.'], ['transformer.h.22.'], ['transformer.h.23.']]
